directories:
  output: release
  buildResources: build
extends: null
appId: com.boehmtech.productivity-tracker
productName: Productivity Tracker
files:
  - filter:
      - public/electron.js
      - electron/**/*
      - node_modules/**/*
extraResources:
  - from: dist/agent.exe
    to: agent.exe
  - from: config.json
    to: config.json
win:
  target:
    - target: nsis
      arch:
        - x64
  publisherName: BoehmTech
  verifyUpdateCodeSignature: false
  signAndEditExecutable: false
  signDlls: false
  sign: null
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: Productivity Tracker
  runAfterFinish: true
mac:
  target:
    - dmg
  category: public.app-category.productivity
electronVersion: 28.3.3
